# Generated by Django 4.2.1 on 2023-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_category"),
        ("carts", "0004_rename_quantity_cartproduct_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="cart_products",
                through="carts.CartProduct",
                to="products.product",
            ),
        ),
    ]
