# Generated by Django 4.2.1 on 2023-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEDIDO REALIZADO", "Pedido Realizado"),
                            ("EM ANDAMENTO", "Em Andamento"),
                            ("ENTREGUE", "Entregue"),
                            ("ADICIONE UM STATUS", "Default"),
                        ],
                        default="ADICIONE UM STATUS",
                        max_length=127,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
