# Generated by Django 4.2.1 on 2023-05-09 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_cartproduct"),
        ("orders", "0002_order_saller_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Cart",
                to="carts.cart",
            ),
            preserve_default=False,
        ),
    ]
