# Generated by Django 4.2.1 on 2023-05-08 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default=django.utils.timezone.now, max_length=127),
            preserve_default=False,
        ),
    ]
